export const SERVICE_CATEGORIES = {
  sports_rehab: {
    name: 'Sports Rehabilitation',
    description: 'Recovery and rehabilitation for sports injuries',
    icon: 'Activity',
    color: 'bg-blue-500',
  },
  pain_management: {
    name: 'Pain Management',
    description: 'Comprehensive pain relief and mobilization therapy',
    icon: 'Heart',
    color: 'bg-red-500',
  },
  physiotherapy: {
    name: 'Physiotherapy',
    description: 'Physical therapy for mobility and strength',
    icon: 'Dumbbell',
    color: 'bg-green-500',
  },
  yoga: {
    name: 'Yoga & Wellness',
    description: 'Yoga sessions for mind-body wellness',
    icon: 'Leaf',
    color: 'bg-purple-500',
  },
} as const;

export const DEFAULT_SERVICES = [
  {
    name: 'Sports Injury Assessment',
    slug: 'sports-injury-assessment',
    category: 'sports_rehab',
    description: 'Comprehensive evaluation of sports-related injuries with personalized recovery plan',
    duration_minutes: 60,
    tier1_price: 1500,
    tier2_price: 1000,
    online_available: true,
    offline_available: true,
    home_visit_available: false,
  },
  {
    name: 'ACL Rehabilitation',
    slug: 'acl-rehabilitation',
    category: 'sports_rehab',
    description: 'Specialized rehabilitation program for ACL injuries and post-surgery recovery',
    duration_minutes: 45,
    tier1_price: 2000,
    tier2_price: 1500,
    online_available: false,
    offline_available: true,
    home_visit_available: true,
  },
  {
    name: 'Back Pain Treatment',
    slug: 'back-pain-treatment',
    category: 'pain_management',
    description: 'Expert treatment for chronic and acute back pain conditions',
    duration_minutes: 45,
    tier1_price: 1200,
    tier2_price: 800,
    online_available: true,
    offline_available: true,
    home_visit_available: true,
  },
  {
    name: 'Neck Pain & Cervical Care',
    slug: 'neck-pain-cervical-care',
    category: 'pain_management',
    description: 'Specialized care for neck pain, cervical spondylosis, and related conditions',
    duration_minutes: 45,
    tier1_price: 1200,
    tier2_price: 800,
    online_available: true,
    offline_available: true,
    home_visit_available: true,
  },
  {
    name: 'Joint Mobilization',
    slug: 'joint-mobilization',
    category: 'pain_management',
    description: 'Manual therapy techniques to improve joint mobility and reduce stiffness',
    duration_minutes: 30,
    tier1_price: 1000,
    tier2_price: 700,
    online_available: false,
    offline_available: true,
    home_visit_available: true,
  },
  {
    name: 'Post-Surgery Rehabilitation',
    slug: 'post-surgery-rehabilitation',
    category: 'physiotherapy',
    description: 'Comprehensive rehabilitation program after orthopedic surgeries',
    duration_minutes: 60,
    tier1_price: 1800,
    tier2_price: 1200,
    online_available: false,
    offline_available: true,
    home_visit_available: true,
  },
  {
    name: 'Stroke Rehabilitation',
    slug: 'stroke-rehabilitation',
    category: 'physiotherapy',
    description: 'Specialized physiotherapy for stroke recovery and neurological conditions',
    duration_minutes: 60,
    tier1_price: 2000,
    tier2_price: 1500,
    online_available: false,
    offline_available: true,
    home_visit_available: true,
  },
  {
    name: 'Geriatric Physiotherapy',
    slug: 'geriatric-physiotherapy',
    category: 'physiotherapy',
    description: 'Specialized care for elderly patients focusing on mobility and independence',
    duration_minutes: 45,
    tier1_price: 1500,
    tier2_price: 1000,
    online_available: false,
    offline_available: true,
    home_visit_available: true,
  },
  {
    name: 'Therapeutic Yoga',
    slug: 'therapeutic-yoga',
    category: 'yoga',
    description: 'Yoga sessions designed for healing and rehabilitation',
    duration_minutes: 60,
    tier1_price: 800,
    tier2_price: 500,
    online_available: true,
    offline_available: true,
    home_visit_available: false,
  },
  {
    name: 'Prenatal Yoga',
    slug: 'prenatal-yoga',
    category: 'yoga',
    description: 'Safe yoga practices for expecting mothers',
    duration_minutes: 45,
    tier1_price: 1000,
    tier2_price: 700,
    online_available: true,
    offline_available: true,
    home_visit_available: false,
  },
  {
    name: 'Stress Relief & Meditation',
    slug: 'stress-relief-meditation',
    category: 'yoga',
    description: 'Guided meditation and breathing exercises for stress management',
    duration_minutes: 45,
    tier1_price: 600,
    tier2_price: 400,
    online_available: true,
    offline_available: true,
    home_visit_available: false,
  },
] as const;

export const APPOINTMENT_MODES = {
  online: {
    name: 'Online Consultation',
    description: 'Video call with doctor via Google Meet',
    icon: 'Video',
  },
  offline: {
    name: 'Clinic Visit',
    description: 'In-person consultation at the clinic',
    icon: 'Building2',
  },
  home_visit: {
    name: 'Home Visit',
    description: 'Doctor visits your home (Premium)',
    icon: 'Home',
  },
} as const;

export const APPOINTMENT_STATUSES = {
  pending: { label: 'Pending', color: 'bg-yellow-100 text-yellow-800' },
  confirmed: { label: 'Confirmed', color: 'bg-blue-100 text-blue-800' },
  completed: { label: 'Completed', color: 'bg-green-100 text-green-800' },
  cancelled: { label: 'Cancelled', color: 'bg-red-100 text-red-800' },
  no_show: { label: 'No Show', color: 'bg-gray-100 text-gray-800' },
} as const;

export const PAYMENT_STATUSES = {
  pending: { label: 'Pending', color: 'bg-yellow-100 text-yellow-800' },
  paid: { label: 'Paid', color: 'bg-green-100 text-green-800' },
  refunded: { label: 'Refunded', color: 'bg-blue-100 text-blue-800' },
  failed: { label: 'Failed', color: 'bg-red-100 text-red-800' },
} as const;
